#!/bin/sh /etc/rc.common
START=90

drcom_up()
{
	local enable
	config_get_bool enable $1 enable
	if [ $enable ]; then
	transdrcom
	drcom &
	sleep 3
	echo "Dr.COM Client is started"
	else
	stop
	fi
}

start()
{
	rm -rf /etc/config/drcom.conf
	config_load drcom
	config_foreach drcom_up
}

stop()
{
	killall python /bin/drcom
	echo "Dr.COM Client is stopped"
}
